// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: order.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orderservice_CreateOder_FullMethodName = "/proto.Orderservice/CreateOder"
)

// OrderserviceClient is the client API for Orderservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderserviceClient interface {
	CreateOder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderserviceClient(cc grpc.ClientConnInterface) OrderserviceClient {
	return &orderserviceClient{cc}
}

func (c *orderserviceClient) CreateOder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, Orderservice_CreateOder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderserviceServer is the server API for Orderservice service.
// All implementations must embed UnimplementedOrderserviceServer
// for forward compatibility.
type OrderserviceServer interface {
	CreateOder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	mustEmbedUnimplementedOrderserviceServer()
}

// UnimplementedOrderserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderserviceServer struct{}

func (UnimplementedOrderserviceServer) CreateOder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOder not implemented")
}
func (UnimplementedOrderserviceServer) mustEmbedUnimplementedOrderserviceServer() {}
func (UnimplementedOrderserviceServer) testEmbeddedByValue()                      {}

// UnsafeOrderserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderserviceServer will
// result in compilation errors.
type UnsafeOrderserviceServer interface {
	mustEmbedUnimplementedOrderserviceServer()
}

func RegisterOrderserviceServer(s grpc.ServiceRegistrar, srv OrderserviceServer) {
	// If the following call pancis, it indicates UnimplementedOrderserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orderservice_ServiceDesc, srv)
}

func _Orderservice_CreateOder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderserviceServer).CreateOder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orderservice_CreateOder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderserviceServer).CreateOder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orderservice_ServiceDesc is the grpc.ServiceDesc for Orderservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orderservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Orderservice",
	HandlerType: (*OrderserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOder",
			Handler:    _Orderservice_CreateOder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
